name = "bet62apostasesportivas"
main = "src/worker/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
account_id = "ca04a31d62caccd4774fd850d109bb91"
keep_vars = true

[triggers]
crons = ["*/5 * * * *"]

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "CHANGE_ME"
ADMIN_TOKEN = "CHANGE_ME"
APP_MODE = "REAL"
BETTING_ENABLED = "1"
LICENSED = "1"
BLOCKED_COUNTRIES = ""
REAL_FEED_ENABLED = "1"
DEV_FAKE_MATCH_DETAIL = "false"
NODE_ENV = "production"
API_SPORTS_SEASON = "2025"
ODDS_API_BOOKMAKERS = "Bet365,1xbet,Betano,Betclic,Superbet"
MEDIA_PROXY_BASE = ""
PAYPAL_CLIENT_ID = ""
PAYPAL_CLIENT_SECRET = ""
PAYPAL_ENVIRONMENT = "sandbox"
FRONTEND_URL = "https://www.bet62.plus"

[[d1_databases]]
binding = "DB"
database_name = "bet62-db"
database_id = "ebaef170-b999-47d6-887d-24c5e16a674b"
preview_database_id = "ebaef170-b999-47d6-887d-24c5e16a674b"
migrations_dir = "migrations"

[env.dev]
name = "bet62-api-dev"
account_id = "ca04a31d62caccd4774fd850d109bb91"
triggers = { crons = ["*/5 * * * *"] }

[env.dev.vars]
ENVIRONMENT = "dev"
APP_MODE = "REAL"
BETTING_ENABLED = "1"
REAL_FEED_ENABLED = "1"
ADMIN_TOKEN = "CHANGE_ME"
JWT_SECRET = "CHANGE_ME"
LICENSED = ""
BLOCKED_COUNTRIES = ""
DEV_FAKE_MATCH_DETAIL = "false"
NODE_ENV = "production"
API_SPORTS_SEASON = "2025"
ODDS_API_BOOKMAKERS = "Bet365,1xbet,Betano,Betclic,Superbet"
MEDIA_PROXY_BASE = ""

[[env.dev.d1_databases]]
binding = "DB"
database_name = "bet62-db"
database_id = "ebaef170-b999-47d6-887d-24c5e16a674b"

[env.production]
name = "bet62apostasesportivas"
account_id = "ca04a31d62caccd4774fd850d109bb91"
triggers = { crons = ["*/5 * * * *"] }

[env.production.vars]
ENVIRONMENT = "production"
APP_MODE = "REAL"
BETTING_ENABLED = "1"
REAL_FEED_ENABLED = "1"
JWT_SECRET = "CHANGE_ME"
ADMIN_TOKEN = "CHANGE_ME"
LICENSED = "1"
BLOCKED_COUNTRIES = ""
DEV_FAKE_MATCH_DETAIL = "false"
NODE_ENV = "production"
API_SPORTS_SEASON = "2025"
ODDS_API_BOOKMAKERS = "Bet365,Betano,Superbet,Unibet,Betfair"
MEDIA_PROXY_BASE = ""
FRONTEND_URL = "https://www.bet62.plus"

[[env.production.d1_databases]]
binding = "DB"
database_name = "bet62-db"
database_id = "ebaef170-b999-47d6-887d-24c5e16a674b"
