version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      REDIS_URL: "redis://redis:6379/0"
      IMAGE_DIR: "/data/images"
    depends_on:
      - redis
    volumes:
      - ./data:/data

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    env_file:
      - .env
    environment:
      REDIS_URL: "redis://redis:6379/0"
      IMAGE_DIR: "/data/images"
    depends_on:
      - redis
    volumes:
      - ./data:/data
